import os
import sqlite3
from datetime import datetime
from fpdf import FPDF

# Setup dynamic paths
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(script_dir)
db_path = os.path.join(project_root, "data", "sap_system.db")
log_path = os.path.join(project_root, "sapmnt", "PRD", "logs", "SM21_log.txt")
reports_dir = os.path.join(project_root, "reports")

class SAPReportPDF(FPDF):
    def header(self):
        # Header: Left aligned text, Right aligned page number
        self.set_font("helvetica", "B", 8)
        self.cell(100, 10, "SAP Basis Operations - CONFIDENTIAL", align="L")
        self.cell(90, 10, f"Page {self.page_no()}", align="R")
        self.ln(15)

    def footer(self):
        # Footer: Centered timestamp at the bottom
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.cell(0, 10, f"Report generated automatically at {timestamp}", align="C")

def generate_pdf():
    print("\n[Running: PDF Report Generation]")
    pdf = SAPReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # ---------------------------------------------------------
    # PAGE 1: Title Page
    # ---------------------------------------------------------
    pdf.add_page()
    pdf.set_font("helvetica", "B", 24)
    pdf.ln(60)
    pdf.cell(0, 15, "SAP BASIS DAILY OPERATIONS REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 14)
    pdf.cell(0, 10, "System: PRD (Production) | Environment: On-Premise SAP ERP", align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(5)
    current_date = datetime.now().strftime("%B %d, %Y - %H:%M")
    pdf.cell(0, 10, current_date, align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(20)
    # Divider line
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(10)
    
    pdf.set_font("helvetica", "", 12)
    description = "This report was automatically generated by the SAP Basis Infrastructure & Monitoring Automation Tool. It summarizes system health, security audit findings, and log analysis for the reporting period."
    pdf.multi_cell(0, 8, description, align="C")

    # Connect to DB for remaining pages
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # ---------------------------------------------------------
    # PAGE 2: System Health Summary
    # ---------------------------------------------------------
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "SYSTEM HEALTH SUMMARY", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    cursor.execute("SELECT CPU_USAGE, RAM_USAGE, DISK_USAGE, DB_LATENCY_MS, STATUS FROM SMSLOG ORDER BY TIMESTAMP DESC LIMIT 1")
    row = cursor.fetchone()
    if row:
        cpu, ram, disk, latency, status = row
    else:
        cpu, ram, disk, latency, status = (0, 0, 0, 0, "NO DATA")

    # Table Header
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(50, 10, "Metric", border=1)
    pdf.cell(40, 10, "Value", border=1)
    pdf.cell(50, 10, "Threshold", border=1)
    pdf.cell(50, 10, "Status", border=1, new_x="LMARGIN", new_y="NEXT")

    # Table Rows
    pdf.set_font("helvetica", "", 12)
    metrics = [
        ("CPU Usage", f"{cpu}%", "< 80%", "OK" if cpu < 80 else "WARNING/CRITICAL"),
        ("RAM Usage", f"{ram}%", "< 85%", "OK" if ram < 85 else "WARNING/CRITICAL"),
        ("Disk Usage", f"{disk}%", "< 90%", "OK" if disk < 90 else "WARNING/CRITICAL"),
        ("Database Latency", f"{latency:.2f} ms", "< 500 ms", "OK" if latency < 500 else "WARNING/CRITICAL"),
        ("Overall Status", "-", "-", status)
    ]

    for m in metrics:
        pdf.cell(50, 10, m[0], border=1)
        pdf.cell(40, 10, m[1], border=1)
        pdf.cell(50, 10, m[2], border=1)
        pdf.cell(50, 10, m[3], border=1, new_x="LMARGIN", new_y="NEXT")

    # ---------------------------------------------------------
    # PAGE 3: Security Audit Summary
    # ---------------------------------------------------------
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "SECURITY AUDIT SUMMARY", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    cursor.execute("SELECT COUNT(*) FROM USR02")
    total_users = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM USR02 WHERE UFLAG = 0")
    active_users = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM USR02 WHERE UFLAG IN (64, 128)")
    locked_users = cursor.fetchone()[0]

    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, f"Total Users Evaluated: {total_users}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Active Compliant Users: {active_users}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Locked/Disabled Users: {locked_users}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    cursor.execute("SELECT USERNAME, VIOLATION_TYPE, ACTION_TAKEN, SEVERITY, TIMESTAMP FROM SECURITY_AUDIT WHERE RESOLVED = 0")
    violations = cursor.fetchall()

    pdf.set_font("helvetica", "B", 10)
    pdf.cell(30, 10, "Username", border=1)
    pdf.cell(50, 10, "Violation Type", border=1)
    pdf.cell(45, 10, "Action Taken", border=1)
    pdf.cell(25, 10, "Severity", border=1)
    pdf.cell(40, 10, "Timestamp", border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "", 9)
    for i, v in enumerate(violations):
        if i >= 15:
            pdf.set_font("helvetica", "I", 10)
            pdf.cell(0, 10, f"... and {len(violations)-15} more violations (see full text audit report)", new_x="LMARGIN", new_y="NEXT")
            break
        pdf.cell(30, 10, str(v[0]), border=1)
        pdf.cell(50, 10, str(v[1]), border=1)
        pdf.cell(45, 10, str(v[2]), border=1)
        pdf.cell(25, 10, str(v[3]), border=1)
        # Format timestamp to fit column: show only date and HH:MM
        short_time = str(v[4])[:-3] 
        pdf.cell(40, 10, short_time, border=1, new_x="LMARGIN", new_y="NEXT")

    # ---------------------------------------------------------
    # PAGE 4: Log Analysis Summary
    # ---------------------------------------------------------
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "SYSTEM LOG ANALYSIS (Transaction SM21)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    keywords = ['CRITICAL', 'DB_ERROR', 'MEMORY_LOW', 'WARNING', 'INFO']
    keyword_counts = {kw: 0 for kw in keywords}
    critical_lines = []

    try:
        with open(log_path, 'r') as f:
            for line in f:
                for kw in keywords:
                    if kw in line:
                        keyword_counts[kw] += 1
                        if kw in ['CRITICAL', 'DB_ERROR', 'MEMORY_LOW']:
                            critical_lines.append(line.strip())
    except FileNotFoundError:
        pass

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(95, 10, "Keyword", border=1)
    pdf.cell(95, 10, "Occurrences", border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "", 12)
    for kw, count in keyword_counts.items():
        pdf.cell(95, 10, kw, border=1)
        pdf.cell(95, 10, str(count), border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Critical Log Lines Found (Top 10):", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 9)
    for line in critical_lines[:10]:
        pdf.multi_cell(0, 6, line)
        pdf.ln(1)

    pdf.ln(10)
    pdf.set_font("helvetica", "I", 10)
    pdf.cell(0, 10, "Full log file available at: sapmnt/PRD/logs/SM21_log.txt", new_x="LMARGIN", new_y="NEXT")

    # Save PDF
    conn.close()
    
    timestamp_for_file = datetime.now().strftime("%Y-%m-%d")
    filename = f"SAP_Daily_Report_{timestamp_for_file}.pdf"
    filepath = os.path.join(reports_dir, filename)
    
    pdf.output(filepath)
    print(f"✅ Professional PDF Report successfully generated!")
    print(f"📄 Saved to: {os.path.relpath(filepath, project_root)}")
    return filepath

if __name__ == "__main__":
    generate_pdf()